//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 06:12:39 PM WEST 
//




import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="smartphone">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="processor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="screenTechnology" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="screenSizeInches" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="screenSizePx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smartphone"
})
@XmlRootElement(name = "smartphonelist")
public class Smartphonelist {

    @XmlElement(required = true)
    protected Smartphonelist.Smartphone smartphone;

    /**
     * Gets the value of the smartphone property.
     * 
     * @return
     *     possible object is
     *     {@link Smartphonelist.Smartphone }
     *     
     */
    public Smartphonelist.Smartphone getSmartphone() {
        return smartphone;
    }

    /**
     * Sets the value of the smartphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Smartphonelist.Smartphone }
     *     
     */
    public void setSmartphone(Smartphonelist.Smartphone value) {
        this.smartphone = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="processor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="screenTechnology" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="screenSizeInches" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="screenSizePx" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "processor",
        "screenTechnology",
        "screenSizeInches",
        "screenSizePx",
        "resolution",
        "price"
    })
    public static class Smartphone {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String processor;
        @XmlElement(required = true)
        protected String screenTechnology;
        @XmlElement(required = true)
        protected String screenSizeInches;
        @XmlElement(required = true)
        protected String screenSizePx;
        @XmlElement(required = true)
        protected String resolution;
        protected double price;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the processor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProcessor() {
            return processor;
        }

        /**
         * Sets the value of the processor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProcessor(String value) {
            this.processor = value;
        }

        /**
         * Gets the value of the screenTechnology property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenTechnology() {
            return screenTechnology;
        }

        /**
         * Sets the value of the screenTechnology property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenTechnology(String value) {
            this.screenTechnology = value;
        }

        /**
         * Gets the value of the screenSizeInches property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenSizeInches() {
            return screenSizeInches;
        }

        /**
         * Sets the value of the screenSizeInches property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenSizeInches(String value) {
            this.screenSizeInches = value;
        }

        /**
         * Gets the value of the screenSizePx property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScreenSizePx() {
            return screenSizePx;
        }

        /**
         * Sets the value of the screenSizePx property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScreenSizePx(String value) {
            this.screenSizePx = value;
        }

        /**
         * Gets the value of the resolution property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResolution() {
            return resolution;
        }

        /**
         * Sets the value of the resolution property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResolution(String value) {
            this.resolution = value;
        }

        /**
         * Gets the value of the price property.
         * 
         */
        public double getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         */
        public void setPrice(double value) {
            this.price = value;
        }

        public String toString(){
            return  "Nome: " + name
                    + "\nProcessador:" + processor
                    + "\nTecnologia de ecrã: " + screenTechnology
                    + "\nTamanho do ecrã: " + screenSizeInches + " " + screenSizePx
                    + "\nResolução Máxima: " + resolution
                    + "\nPrice: " + price + "€"
                    + "\n--------------------";
        }

    }

}
