//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 01:32:50 AM WEST 
//




import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="processor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenTechnology" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenSizeInches" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="screenSizePx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resolution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brand",
    "model",
    "processor",
    "screenTechnology",
    "screenSizeInches",
    "screenSizePx",
    "resolution",
    "price"
})
public class Smartphone {

    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String model;
    @XmlElement(required = true)
    protected String processor;
    @XmlElement(required = true)
    protected String screenTechnology;
    @XmlElement(required = true)
    protected String screenSizeInches;
    @XmlElement(required = true)
    protected String screenSizePx;
    @XmlElement(required = true)
    protected String resolution;
    protected double price;
    @XmlAttribute(name = "id")
    protected Byte id;

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

    /**
     * Gets the value of the screenTechnology property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenTechnology() {
        return screenTechnology;
    }

    /**
     * Sets the value of the screenTechnology property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenTechnology(String value) {
        this.screenTechnology = value;
    }

    /**
     * Gets the value of the screenSizeInches property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenSizeInches() {
        return screenSizeInches;
    }

    /**
     * Sets the value of the screenSizeInches property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenSizeInches(String value) {
        this.screenSizeInches = value;
    }

    /**
     * Gets the value of the screenSizePx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScreenSizePx() {
        return screenSizePx;
    }

    /**
     * Sets the value of the screenSizePx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScreenSizePx(String value) {
        this.screenSizePx = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolution(String value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(double value) {
        this.price = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setId(Byte value) {
        this.id = value;
    }

    public String toString(){
        return "\nBrand: " + brand
                + "\nModel: " + model
                + "\nProcessador:" + processor
                + "\nTecnologia de ecrã: " + screenTechnology
                + "\nTamanho do ecrã: " + screenSizeInches + " " + screenSizePx
                + "\nResolução Máxima: " + resolution
                + "\nPrice: " + price + "€"
                + "\n--------------------";

    }


}
